# Site settings
title: Luke Webster
tagline: "Personal portfolio site"
url: "https://lukew244.github.io/" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
twitter: twusername
github_username: lukew244
email: luke.webster86@gmail.com


# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
